export const REDUCER_EMPLOYEES = "EMPLOYEES";

export const GET_EMPLOYEES_REQUEST = "GET_EMPLOYEES_REQUEST";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_FAILURE = "GET_EMPLOYEES_FAILURE";

export const CREATE_EMPLOYEES_REQUEST = "CREATE_EMPLOYEES_REQUEST";
export const CREATE_EMPLOYEES_SUCCESS = "CREATE_EMPLOYEES_SUCCESS";
export const CREATE_EMPLOYEES_FAILURE = "CREATE_EMPLOYEES_FAILURE";

export const EDIT_EMPLOYEES_REQUEST = "EDIT_EMPLOYEES_REQUEST";
export const EDIT_EMPLOYEES_SUCCESS = "EDIT_EMPLOYEES_SUCCESS";
export const EDIT_EMPLOYEES_FAILURE = "EDIT_EMPLOYEES_FAILURE";

export const DELETE_EMPLOYEES_REQUEST = "DELETE_EMPLOYEES_REQUEST";
export const DELETE_EMPLOYEES_SUCCESS = "DELETE_EMPLOYEES_SUCCESS";
export const DELETE_EMPLOYEES_FAILURE = "DELETE_EMPLOYEES_FAILURE";
